# Generated by Django 4.1.1 on 2022-09-28 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='super',
            old_name='seconday_ability',
            new_name='secondary_ability',
        ),
    ]
